// Fictional scenarios: scores measure these exercises, not real financial wellbeing.
export const sorting = [
 {title:'Your ride to class',text:'The bus is your only reliable way to reach campus. You are buying the basic monthly pass.',answer:0,why:'In this situation, reliable transport is a need: it lets you attend class.'},
 {title:'A phone upgrade',text:'Your current phone works well. A new model has a better camera and a limited-time discount.',answer:1,why:'An optional upgrade is a want. A discount does not turn it into a need.'},
 {title:'Dinner at home',text:'You are buying basic groceries to prepare meals for the week.',answer:0,why:'Food is a need. How much you spend and the options available still matter.'},
 {title:'The concert ticket',text:'Your favorite artist is visiting. The ticket costs money you could otherwise save.',answer:1,why:'Entertainment is a want, and wants can belong in a budget. Plan for them after essentials.'},
 {title:'A required textbook',text:'Your course requires this book. There is no library copy, free version, or borrowing option available.',answer:0,why:'Given these constraints, the book supports your education and is a need.'},
 {title:'One more subscription',text:'You already have a streaming service and want another one for a single new show.',answer:1,why:'This is optional entertainment. Checking recurring costs can help you protect your budget.'},
 {title:'Replacing broken glasses',text:'Your glasses broke, and you need them to read and travel safely. You choose a basic replacement.',answer:0,why:'The context matters: this replacement supports your health and daily life.'},
 {title:'Coffee with an upgrade',text:'You have coffee at home but want a specialty drink on your way to campus.',answer:1,why:'This purchase is a want in this scenario. You can still choose it when your budget allows.'}
];
export const scams = [
 {title:'“Your account closes in 10 minutes”',from:'Text message · Unknown sender',text:'URGENT: Your bank account will be locked. Sign in using this link now to keep your money safe.',options:['Open the link before time runs out','Open the bank’s official app independently','Reply with my password'],answer:1,why:'Urgency and an unexpected sign-in link are warning signs. Verify through an official app or a number you already trust.'},
 {title:'A scholarship with a catch',from:'Direct message · “Campus awards”',text:'Congratulations! You won a scholarship you never applied for. Send a gift-card code to release your award.',options:['Buy the gift card','Send half the amount first','Check with the official financial-aid office'],answer:2,why:'An unexpected award requiring gift-card payment is a major red flag. Confirm with the official office without using the message’s contact details.'},
 {title:'The one-time code',from:'Phone call · Claimed bank support',text:'We detected fraud. Read us the code we just sent so we can secure your account.',options:['Hang up and contact the bank independently','Read the code to stop the fraud','Share only the last few digits'],answer:0,why:'Do not share a one-time login code with an unsolicited caller. Caller ID can be faked; use a trusted contact method.'},
 {title:'Guaranteed growth?',from:'Social message · Investment group',text:'Double your savings this week. Guaranteed returns, no risk. Send money today to reserve your spot.',options:['Send a small trial payment','Decline and investigate independently','Invite friends for the bonus'],answer:1,why:'Promises of high guaranteed returns with no risk and pressure to act are warning signs. A small payment is still money at risk.'},
 {title:'The overpaid campus job',from:'Email · New remote employer',text:'Deposit this check, then send part of it to our equipment supplier before you start work.',options:['Send the money once the balance appears','Keep a little extra for myself','Stop and verify the employer independently'],answer:2,why:'A displayed balance does not prove a check is valid. Requests to forward part of a check are a common scam pattern.'},
 {title:'A friend needs help',from:'Chat · Familiar profile photo',text:'Lost my phone! I need money urgently. Please do not call. Send it to this new account.',options:['Verify through another known contact method','Send it because the photo matches','Ask for another profile photo'],answer:0,why:'A familiar account may be impersonated or compromised. Verify independently before sending money.'}
];
export const events = [
 {title:'Your laptop stops charging.',text:'You need it for class. A campus technician confirms a replacement charger will fix it.',options:[{text:'Buy the compatible charger',cost:60,points:1,why:'You solve the actual problem while protecting most of your reserve.'},{text:'Replace the entire laptop',cost:300,points:0,why:'The confirmed repair costs less. Replacing the whole laptop uses much more of your cushion.'}]},
 {title:'A weekend with friends.',text:'Your friends suggest a trip. You can also meet them locally. Choose an option that fits your plan.',options:[{text:'Suggest a local hangout',cost:20,points:1,why:'A lower-cost alternative leaves room for connection and your savings goal.'},{text:'Take the weekend trip',cost:150,points:0,why:'Enjoyment matters, but this trip uses much more of the money reserved for your goal.'},{text:'Skip this one',cost:0,points:1,why:'Saying no is an option when protecting a goal. A free meetup could work another time.'}]},
 {title:'The bike repair.',text:'Your bike needs a safety repair. It is your transport for the rest of this fictional month.',options:[{text:'Pay for the safety repair',cost:70,points:1,why:'Protecting safe, reliable transport is a useful job for an emergency reserve.'},{text:'Buy a replacement bike',cost:240,points:0,why:'A replacement costs more than the confirmed repair in this scenario.'}]}
];
export function reserve(food,fun) { return 1000-450-food-fun; }
export function budgetScore(balance,decisions) {return Math.round(Math.max(0,Math.min(1,balance/150))*40+Math.max(0,Math.min(3,decisions))*20);}
export function shuffled(items,random=Math.random) {const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;}
export function validRecord(value) {return value && Number.isInteger(value.best) && value.best>=0 && value.best<=100 && Number.isInteger(value.plays) && value.plays>=0 && value.plays<1000000;}
