// Content is separate from page behavior. Add future lesson translations here.
// Amounts are fictional money units, not exchange-rate conversions.
const MoneyGuideModules = (() => {
  function question(prompt, options, answer, explanation) {
    return { prompt, options, answer, explanation };
  }
  function lesson(title, paragraphs, example, takeaway, check) {
    return { title, paragraphs, example, takeaway, check };
  }
  const q = question;
  const l = lesson;
  return [
    {
      id: 1, title: 'Money Fundamentals', icon: '01',
      description: 'Understand what comes in, what goes out, and what matters to you.',
      introduction: 'Money is a tool for exchanging value, comparing prices, and storing purchasing power. Learning to notice your everyday choices is the first step toward using that tool deliberately.',
      objectives: ['Separate income, expenses, needs, and wants.', 'Calculate a simple net worth.', 'Turn a wish into a practical financial goal.'],
      lessons: [
        l('Know your money flow', [
          'Income is money you receive, such as wages from a campus job. Expenses are money you spend, such as rent, transport, or food. A loan brings cash into your account, but it also creates a repayment obligation; it is not earned income.',
          'Needs support your basic living, health, or ability to study and work. Wants improve comfort or enjoyment. Context matters: internet access may be essential for class, while a premium entertainment subscription is usually optional.'
        ], 'Sam receives 600 from work and spends 420 on essentials and 80 on entertainment. That leaves 100: 600 − 420 − 80. Sam can give this remainder a job, such as saving.', 'Track what arrives and leaves before deciding what to change.', q('A student needs a laptop for required coursework. What is the best interpretation?', ['Every laptop is a want.', 'A suitable basic laptop can be a need; premium upgrades may be wants.', 'The most expensive model is always necessary.'], 1, 'The purpose and available alternatives matter more than the category name.')),
        l('What you own and what you owe', [
          'An asset is something you own with financial value, such as savings or a bicycle you could sell. A liability is a debt or amount owed, such as a loan balance. Estimate assets at realistic current values, not their original prices.',
          'Net worth = total assets − total liabilities. It is a snapshot at a point in time, not your monthly income or a measure of your worth as a person. Students may have negative net worth while studying.'
        ], 'Amina has 900 in savings and a bicycle worth 100. She owes 350. Assets are 1,000, liabilities are 350, and net worth is 650.', 'Use assets minus debts to understand your starting point.', q('You own assets worth 800 and owe 1,100. What is your net worth?', ['300', '1,900', '−300'], 2, '800 − 1,100 = −300. A negative number means debts exceed assets.')),
        l('Turn goals into habits', [
          'A useful financial goal names an amount, a purpose, and a deadline. Break it into actions you can repeat. Saving 120 for textbooks in three months means setting aside 40 each month, assuming no interest.',
          'Simple habits include reviewing transactions weekly, checking due dates, and pausing before optional purchases. Opportunity cost means the next-best use you give up when choosing one option. Plans can change when your circumstances do.'
        ], 'Leo wants a 60 concert ticket and also needs 60 more for a course fee. Buying the ticket means delaying the fee goal unless another expense changes.', 'Make the next step small, specific, and connected to your priorities.', q('Which goal gives you a clear action?', ['Be rich someday.', 'Save 150 for books over five months by setting aside 30 monthly.', 'Never spend anything.'], 1, 'The amount, purpose, deadline, and monthly action are clear.'))
      ],
      vocabulary: [['Money','A tool used to exchange value, compare prices, and store purchasing power.'],['Income','Money received, such as earnings from work.'],['Expense','Money spent on goods, services, or obligations.'],['Need','Something essential in your circumstances.'],['Want','Something desirable that is not essential.'],['Asset','Something you own with financial value.'],['Liability','An amount you owe.'],['Net worth','Total assets minus total liabilities.'],['Financial goal','A money-related target with a purpose and timeframe.'],['Opportunity cost','The next-best alternative you give up when making a choice.']],
      summary: 'Notice your income and expenses, separate essentials from optional spending, and calculate what you own minus what you owe. Choose one specific goal and a repeatable habit to support it.',
      assessment: [
        q('You earn 700 and spend 550 this month. How much remains?', ['150','550','1,250'],0,'700 − 550 = 150.'),
        q('A loan deposits 500 into your account. What else changes?', ['Nothing; it is free income.','You now have a repayment obligation.','Your salary increases.'],1,'Borrowed cash creates a liability.'),
        q('Your course requires internet. Which is most reasonable?', ['All internet is a want.','Only a premium plan counts as a need.','Basic access can be a need; optional upgrades may be wants.'],2,'Needs depend on your circumstances.'),
        q('Assets are 2,000 and debts are 800. Net worth is:', ['2,800','1,200','800'],1,'Net worth = 2,000 − 800.'),
        q('Which belongs under liabilities?', ['A student loan balance','Cash savings','A bicycle you own outright'],0,'A loan balance is money owed.'),
        q('A bike cost 400 but could now sell for 150. Which value is useful in a current net-worth estimate?', ['400','550','150'],2,'Use a realistic current value.'),
        q('You want 240 for books in six months. Ignoring interest, save monthly:', ['60','40','24'],1,'240 ÷ 6 = 40.'),
        q('Buying a game means postponing a trip. The postponed trip is an example of:', ['Opportunity cost','Earned income','A liability in every case'],0,'It is the alternative given up.'),
        q('A student has negative net worth. Which conclusion follows?', ['They have failed at life.','They cannot make a plan.','Their debts currently exceed their assets.'],2,'Net worth is a financial snapshot, not a personal judgment.'),
        q('What is a useful first habit when spending feels unclear?', ['Guess where money went.','Review actual transactions weekly.','Ignore small expenses.'],1,'Tracking provides evidence for decisions.')
      ], sources: [['CFPB financial education tools','https://www.consumerfinance.gov/consumer-tools/']]
    },
    {
      id: 2, title: 'Budgeting', icon: '02', description: 'Give your monthly income a practical plan.',
      introduction: 'A budget is a flexible plan for income, spending, and saving over a period of time. It helps you spot tradeoffs before you run out of money.',
      objectives: ['Distinguish fixed and variable expenses.', 'Build a balanced monthly plan.', 'Use guidelines flexibly and adjust with actual spending.'],
      lessons: [
        l('Build from take-home income', ['Start with income you can reasonably expect to have available after deductions. If work hours vary, use a cautious estimate and plan what to do with extra income.', 'Fixed expenses stay fairly similar each period, like rent. Variable expenses change, like groceries or electricity. Fixed does not automatically mean essential: a subscription can be fixed and optional.'], 'Maya expects 1,000 in take-home pay. She lists 450 rent, 180 food, 70 transport, 50 phone, 100 savings, and 150 other spending. The total is 1,000.', 'Plan with money you can actually use, including both saving and spending.', q('Your weekly shifts vary. Which budgeting starting point is safer?', ['Assume your highest-ever pay every month.','Use a conservative income estimate.','Ignore income and only list wants.'],1,'A cautious estimate reduces the risk of planning expenses you cannot cover.')),
        l('Try a guideline, not a rigid rule', ['The 50/30/20 guideline suggests assigning 50% of take-home income to needs, 30% to wants, and 20% to savings and debt repayment goals. Required minimum debt payments still need to be covered in your essential obligations; avoid counting them twice.', 'Local housing costs, family duties, and student income can make these percentages unrealistic. Use the guideline to notice patterns, then choose a plan that fits. A balanced budget assigns no more than available income.'], 'On 1,200, the guideline gives 600 for needs, 360 for wants, and 240 for savings/debt goals. If rent alone is 650, adapt other categories instead of pretending the guideline fits.', 'A useful budget fits your reality and makes tradeoffs visible.', q('Essential costs exceed 50% of income. What should you do?', ['Stop budgeting.','Hide essential costs.','Adjust the plan and look for realistic options.'],2,'The percentages are a starting point, not a pass/fail test.')),
        l('Review, adjust, and plan ahead', ['Common mistakes are forgetting annual fees, planning with gross pay, underestimating small purchases, and treating a budget as permanent. Divide predictable irregular costs by the months remaining and save gradually.', 'Compare the plan with actual spending. If one category goes over, move money from another category or revise future plans. Track bill dates as well as monthly totals: a budget can balance while the account runs low before payday.'], 'A 120 course fee is due in four months. Setting aside 30 each month makes it predictable. If food costs 20 extra, Maya reduces another optional category by 20.', 'Review regularly; an adjustment is useful information, not a failure.', q('An annual membership renewal is expected. Where does it belong?', ['In planned irregular expenses.','Only in emergency spending.','Nowhere until it is overdue.'],0,'Known future costs should be planned for.'))
      ],
      vocabulary: [['Budget','A plan for income, spending, and saving over a period.'],['Take-home pay','Pay available after payroll deductions.'],['Fixed expense','A cost that stays fairly similar each period.'],['Variable expense','A cost that changes between periods.'],['Needs','Essential costs in your circumstances.'],['Wants','Optional spending that improves comfort or enjoyment.'],['50/30/20','A flexible needs/wants/saving-and-debt guideline for take-home income.'],['Sinking fund','Money set aside gradually for a known future cost.'],['Deficit','The amount by which planned spending exceeds available income.'],['Cash flow','The timing and movement of money in and out.']],
      summary: 'List realistic take-home income, account for fixed, variable, and irregular costs, and give saving a place. Compare your plan with real spending and adjust it as life changes.',
      assessment: [
        q('Gross pay is 1,500 and take-home pay is 1,200. Which is the better monthly spending starting point?', ['1,500','1,200','2,700'],1,'Take-home pay reflects deductions.'),
        q('Which cost is usually variable?', ['Rent on a fixed lease','A fixed subscription','Groceries'],2,'Grocery spending changes with choices and prices.'),
        q('Income is 900 and planned spending plus saving is 980. What adjustment is needed?', ['Reduce allocations or add reliable income by 80.','No adjustment.','Spend 80 more.'],0,'The plan is over income by 80.'),
        q('Under 50/30/20, 20% of 1,000 is:', ['20','200','500'],1,'1,000 × 0.20 = 200.'),
        q('Rent makes the needs guideline unrealistic. What is useful?', ['Give up.','Ignore rent.','Adapt the percentages to actual circumstances.'],2,'Guidelines are flexible.'),
        q('A 180 fee is due in six months. Monthly saving needed is:', ['30','60','180'],0,'180 ÷ 6 = 30.'),
        q('Food is 25 over plan. What keeps the budget balanced?', ['Leave all other allocations unchanged.','Reduce another flexible allocation by 25.','Count the overrun as income.'],1,'Reallocating 25 keeps the total unchanged.'),
        q('A monthly streaming subscription is best described as:', ['Always a need','A variable tax','A fixed but optional expense'],2,'Regular pricing does not make a purchase essential.'),
        q('Your month balances but rent is due before payday. What should you examine?', ['Bill and income timing','Only the annual total','Your credit limit as income'],0,'Cash-flow timing can reveal a temporary shortfall.'),
        q('Which habit makes a budget useful over time?', ['Never change it.','Compare actual spending and update it.','Record only large purchases.'],1,'Regular reviews make the plan realistic.')
      ], sources: [['CFPB budgeting resources','https://www.consumerfinance.gov/consumer-tools/educator-tools/your-money-your-goals/']]
    },
    {
      id: 3, title: 'Saving & Emergency Funds', icon: '03', description: 'Build a cushion and work toward the things that matter.',
      introduction: 'Saving sets money aside for a future purpose. A small, repeatable contribution can help you prepare for both planned purchases and unexpected expenses.',
      objectives: ['Distinguish emergencies from planned costs.', 'Create a manageable saving habit.', 'Understand interest, accessibility, and compound growth.'],
      lessons: [
        l('Give savings a purpose', ['Short-term savings cover goals coming soon, such as next semester’s books. Longer-term savings support later plans. Name your goal and deadline, then divide the remaining amount by the number of saving periods.', 'Pay yourself first means planning an affordable saving amount when income arrives, instead of hoping money remains. Cover essential obligations and avoid transfers that trigger overdrafts.'], 'Jules needs 300 in ten months and already has 50. The remaining 250 requires 25 monthly, ignoring interest.', 'Choose an affordable contribution and a clear destination.', q('You have 40 toward a 200 goal due in four months. Save monthly:', ['50','40','160'],1,'(200 − 40) ÷ 4 = 40.')),
        l('Prepare for the unexpected', ['An emergency fund is a cash reserve for unplanned necessary costs or lost income. A known tuition bill belongs in a separate planned-expense fund. Emergency money should be safe and accessible when needed.', 'There is no single right amount for everyone. Start with a realistic small target based on likely surprises, then review it as income, essential costs, and support systems change. Rebuild after using it.'], 'An unexpected repair to the bike you use for work may fit an emergency fund. A predictable annual student fee does not become an emergency just because it was forgotten.', 'Match your cushion to your circumstances, and use it for its purpose.', q('Which is the clearest emergency-fund use?', ['An unexpected essential repair','A planned holiday','A yearly fee known in advance'],0,'Emergency reserves are for necessary surprises, not predictable costs.')),
        l('Understand the account and the growth', ['Savings interest is money the provider pays on eligible deposits. A high-yield savings account describes an account offering a relatively higher rate, not a guaranteed permanent rate. Compare fees, access, eligibility, and local deposit protection as well as yield.', 'Compound growth means returns can earn further returns. In a simplified example, 100 growing at 5% each year becomes 105 after one year and 110.25 after two. Actual rates may change, fees and taxes may apply, and investments can lose value.'], 'Saving 10 each week for 12 weeks adds 120 before interest. A routine can matter more than chasing a slightly higher rate on a small balance.', 'Consistency, safety, and access matter alongside the advertised rate.', q('At a fixed hypothetical 10% annual rate, 100 becomes 110 after a year. The next year’s interest is:', ['10','100','11'],2,'10% of 110 is 11 because previous interest also earns interest.'))
      ],
      vocabulary: [['Saving','Setting money aside for future use.'],['Pay yourself first','Plan a manageable saving contribution when income arrives.'],['Emergency fund','Accessible reserves for necessary unexpected costs or lost income.'],['Short-term goal','A goal with a relatively near deadline.'],['Long-term goal','A goal further in the future.'],['Interest','Money earned on deposits or charged on borrowing.'],['Compound growth','Growth on both the starting amount and accumulated returns.'],['Yield','A measure of return over a period.'],['Liquidity','How easily money can be accessed without major loss or delay.'],['Automatic transfer','A scheduled movement of money between accounts.']],
      summary: 'Give each saving goal a purpose, set a realistic contribution, and keep emergency money accessible. Compare account conditions and understand how interest can compound.',
      assessment: [
        q('You need 360 in twelve months, starting from zero. Monthly saving is:', ['12','30','360'],1,'360 ÷ 12 = 30.'),
        q('Pay yourself first means:', ['Ignore rent.','Save only whatever remains.','Plan an affordable contribution when income arrives.'],2,'The contribution belongs in the plan.'),
        q('Which cost fits a planned-expense fund?', ['Known next-semester books','Unexpected job loss','An urgent unplanned repair'],0,'Books are a predictable expense.'),
        q('Where should emergency money generally be easy to access?', ['An account with a long lockup only','A suitable safe, accessible place','A highly volatile asset only'],1,'Emergencies may require prompt access.'),
        q('After using emergency savings, a useful next step is:', ['Never save again.','Pretend the balance is unchanged.','Gradually rebuild the reserve.'],2,'Using and rebuilding the reserve is part of its purpose.'),
        q('At a hypothetical fixed 5% annual rate, 200 earns in the first year:', ['10','5','100'],0,'200 × 0.05 = 10.'),
        q('After that year, 210 at 5% earns:', ['10','10.50','21'],1,'210 × 0.05 = 10.50.'),
        q('A high advertised savings rate is enough to choose an account:', ['Always','Only if a friend likes it','No; fees, access, and protection also matter'],2,'Yield is one part of the comparison.'),
        q('Your income varies. What is a realistic saving approach?', ['Use affordable contributions and adjust as income changes.','Promise more than you receive.','Never review your plan.'],0,'A flexible routine can be sustainable.'),
        q('How much emergency saving does everyone need?', ['Exactly the same amount','An amount based on their circumstances','Nothing if they have a credit card'],1,'Costs, income stability, and support differ.')
      ], sources: [['CFPB emergency-fund guide','https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/']]
    },
    {
      id: 4, title: 'Banking', icon: '04', description: 'Choose and use everyday banking services with confidence.',
      introduction: 'Bank accounts help you receive, hold, and move money. Understanding the account terms is as important as understanding the app.',
      objectives: ['Compare transaction and saving accounts.', 'Spot fees and understand balances.', 'Use digital banking with safer habits.'],
      lessons: [
        l('Choose the right account for the job', ['Checking accounts, also called current or transaction accounts in some countries, are designed for everyday payments. Savings accounts are generally intended for setting money aside and may pay interest. Access rules vary.', 'A debit card typically uses money in your linked account, unlike a credit card that borrows. Direct deposit sends pay electronically to an account. ATMs allow services such as cash withdrawal; some charge fees.'], 'Nia directs wages to a transaction account, pays bills from it, and moves a planned amount to savings. She checks whether the nearby ATM adds a withdrawal fee.', 'Know where payments come from and what each account is designed to do.', q('You pay using a debit card. The money usually comes from:', ['A new salary payment','Your linked account','An investment profit'],1,'Debit card spending normally draws on your account balance.')),
        l('Read beyond the headline', ['Compare monthly maintenance fees, minimum balance rules, ATM fees, transfer fees, and overdraft terms. An overdraft occurs when payments take an account below zero; depending on the account, transactions may be declined or fees may apply.', 'A displayed balance can differ from funds truly available after pending card transactions or holds. Savings interest rates can change. Check whether the institution and deposit type qualify for protection under the relevant local scheme; limits and rules differ by country.'], 'An account costing 4 per month costs 48 over a year before other fees. A student compares this with a no-monthly-fee account that has suitable access and terms.', 'Compare the total cost, access, and account conditions.', q('A 3 monthly fee costs how much over a year?', ['3','9','36'],2,'3 × 12 = 36.')),
        l('Make security a routine', ['Use unique passwords and multifactor authentication where available. Open the bank’s official app or type its known address rather than following unexpected login links. Never share a one-time login code with someone who contacts you.', 'Review transactions, enable useful alerts, and report suspicious activity promptly through an official contact channel. Protect your PIN at ATMs and sign out of shared devices. Choosing a bank also means considering service access, support, reliability, and your needs.'], 'A text says your account will close unless you enter a code at a link. Instead, you open the official banking app and contact support using a known number.', 'Pause and verify unexpected requests through an independent official channel.', q('A caller claiming to be your bank asks for a login code. What should you do?', ['Share it quickly.','Post it to social media.','Do not share it; verify through official support.'],2,'A login code can let someone access your account.'))
      ],
      vocabulary: [['Checking/current account','An account designed for everyday transactions.'],['Savings account','An account generally designed to hold savings and sometimes earn interest.'],['Debit card','A card that normally spends from a linked account.'],['ATM','A machine that provides banking services such as withdrawals.'],['Direct deposit','An electronic payment sent directly into an account.'],['Overdraft','When payments take an account below zero.'],['Maintenance fee','A regular charge for an account.'],['Available balance','Funds currently available, subject to account rules and pending activity.'],['Multifactor authentication','Using more than one kind of verification to sign in.'],['Phishing','A deceptive attempt to obtain sensitive information or account access.']],
      summary: 'Match accounts to your needs, compare the full fee schedule, and monitor your balance. Use secure sign-in habits and independently verify unexpected messages.',
      assessment: [
        q('Which account is usually designed for frequent bill payments?', ['Checking/current','A locked long-term product only','An insurance policy'],0,'Transaction accounts support everyday payments.'),
        q('A debit card normally spends:', ['Unlimited borrowed money','Money from a linked account','Only interest earned'],1,'Debit is linked to account funds.'),
        q('A fee is 5 each month. Annual cost is:', ['5','10','60'],2,'5 × 12 = 60.'),
        q('A nearby ATM adds a fee. What should you compare?', ['Fee-free network options and account terms','Only the color of the machine','Nothing; ATMs are always free'],0,'ATM access and fees affect total banking cost.'),
        q('Pay arriving electronically into your bank account is:', ['Overdraft','Direct deposit','A credit score'],1,'Direct deposit transfers pay electronically.'),
        q('Your balance shows 100 and a 70 card payment is pending. What is prudent?', ['Spend 100 more without checking.','Ignore the pending payment.','Account for the pending payment before spending.'],2,'Displayed balances may not reflect all obligations.'),
        q('An unfamiliar text asks you to log in. Best response?', ['Open the known official app independently.','Use the link immediately.','Reply with your password.'],0,'Independent verification avoids deceptive links.'),
        q('Which is a stronger sign-in habit?', ['Reuse the same password everywhere.','Use a unique password and multifactor authentication.','Share your PIN with classmates.'],1,'Multiple protections reduce account-access risk.'),
        q('Deposit protection rules:', ['Are identical worldwide','Apply to every product without limits','Depend on the country, institution, and account'],2,'Check local eligibility and limits.'),
        q('An account has a high savings rate but costly fees. You should:', ['Compare net benefit, access, and full terms.','Ignore all fees.','Assume the rate never changes.'],0,'The whole account matters, not only its rate.')
      ], sources: [['CFPB bank accounts resources','https://www.consumerfinance.gov/consumer-tools/bank-accounts/']]
    },
    {
      id: 5, title: 'Credit & Credit Scores', icon: '05', description: 'Understand borrowing records and responsible card use.',
      introduction: 'Credit lets you receive something now and pay later under agreed terms. Credit systems vary by country; this module introduces common concepts, including examples from the United States.',
      objectives: ['Distinguish reports from scores.', 'Understand APR, limits, and minimum payments.', 'Recognize habits that support responsible credit use.'],
      lessons: [
        l('Your record and the number', ['A credit report records information about borrowing accounts and repayment history. A credit score is a model’s numerical estimate of credit risk using information such as that report. You can have more than one score.', 'Payment history, amounts owed relative to limits, length of history, recent applications, and account types can affect commonly used US scores. Models and local systems differ. Review reports through legitimate channels and dispute errors with the relevant provider.'], 'Two students earn similar salaries but have different repayment records. Their scores may differ because a score is not simply a measure of income.', 'Your report is the underlying record; a score is an interpretation of information.', q('You find an account on your report that is not yours. What is useful?', ['Ignore it forever.','Dispute it through the appropriate official process.','Open more cards immediately.'],1,'Incorrect records can affect decisions and should be investigated.')),
        l('Know a card’s price and limits', ['A credit limit is the maximum balance the provider permits under the agreement, not extra income. Credit utilization compares a reported balance with the limit. A 200 balance on a 1,000 limit is 20%. Lower utilization generally supports many scoring models, but there is no universal magic cutoff.', 'APR is an annualized borrowing rate. Actual interest depends on the product and calculation method. The minimum payment is the smallest required payment for that bill; paying only it can leave debt accruing interest for a long time. For cards with a purchase grace period, paying the full statement balance on time generally avoids purchase interest if the conditions are met.'], 'A 1,000 balance at 24% APR would have roughly 20 interest for one month using APR ÷ 12. This is a simplified estimate; real statements may use daily balances and other terms.', 'Read the statement and terms; the minimum due is not the total cost.', q('A 300 balance on a 1,500 limit gives utilization of:', ['5%','50%','20%'],2,'300 ÷ 1,500 = 0.20.')),
        l('Build a responsible routine', ['Track due dates, keep spending within what you can repay, and review statements for errors. Automatic payments can help, but only if your payment account has enough funds. Contact the lender early if payment trouble arises.', 'Common mistakes include treating a limit as income, missing payments, applying repeatedly without a reason, and believing you must carry interest-bearing debt to build credit. Some starter or secured products may help establish history if they report to relevant bureaus, but compare costs and eligibility.'], 'Eli sets a reminder before the due date, checks the statement, and pays the full statement balance when affordable. Eli does not buy extra things just to increase credit activity.', 'Use credit for a purpose you can afford, not to chase a score.', q('Must you pay interest just to build credit history?', ['No; carrying interest-bearing debt is not required.','Yes, always.','Only if your income is low.'],0,'Responsible reported use does not require paying interest.'))
      ],
      vocabulary: [['Credit','An arrangement to receive value now and repay later.'],['Credit report','A record of borrowing and repayment information.'],['Credit score','A model-based numerical estimate of credit risk.'],['Credit limit','The maximum balance permitted under a credit agreement.'],['Utilization','A credit balance compared with its limit.'],['APR','Annual Percentage Rate: an annualized measure of borrowing cost; included fees depend on the product and rules.'],['Minimum payment','The smallest payment required for a billing period.'],['Statement balance','The balance shown at the end of a billing cycle.'],['Grace period','A period that may allow eligible purchases to avoid interest when conditions are met.'],['Secured credit card','A credit card generally backed by a security deposit.']],
      summary: 'Check your borrowing records, understand statement terms, and make payments on time. A limit is not income, and paying only the minimum can make debt costly.',
      assessment: [
        q('A credit report and a credit score are:', ['Exactly the same thing','A record and a model-based number, respectively','Both salary statements'],1,'Reports contain records; scores interpret risk information.'),
        q('A credit limit increases by 500. Your income:', ['Also increases by 500','Doubles','Does not increase'],2,'Borrowing capacity is not income.'),
        q('A 250 balance on a 1,000 limit is:', ['25% utilization','4% utilization','75% utilization'],0,'250 ÷ 1,000 = 25%.'),
        q('What can happen if you pay only the minimum?', ['All debt disappears.','Debt can remain and accrue interest.','APR automatically becomes zero.'],1,'Minimum payments usually leave a balance.'),
        q('At 12% APR, simplified monthly interest on 600 is:', ['72','60','6'],2,'600 × 0.12 ÷ 12 = 6, ignoring actual daily methods.'),
        q('Which habit generally supports a stronger repayment record?', ['Paying on time','Missing due dates','Ignoring statements'],0,'Payment history matters to many scoring models.'),
        q('An incorrect late payment appears on your report. What next?', ['Accept it without checking.','Dispute it using the official process.','Delete your budget.'],1,'Errors should be investigated through proper channels.'),
        q('Do you need to carry interest-bearing debt to build credit?', ['Always','Only on weekends','No'],2,'Paying interest is not required to establish responsible reported use.'),
        q('Before using automatic payments, check:', ['That the payment account can cover them','Only your card color','That you have spent the entire limit'],0,'Insufficient funds can cause failed payments or fees.'),
        q('Which is true of credit scoring?', ['There is one universal score worldwide.','Models and local systems differ.','Income alone determines every score.'],1,'Scores depend on the model and information used.')
      ], sources: [['CFPB credit scores','https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/understand-your-credit-score/']]
    },
    {
      id: 6, title: 'Debt & Loans', icon: '06', description: 'Compare borrowing costs and understand repayment choices.',
      introduction: 'A loan brings future repayment obligations into today’s decision. Whether borrowing is useful depends on purpose, cost, affordability, and risk—not simply the label on the loan.',
      objectives: ['Explain principal, interest, APR, and term.', 'Compare total cost with monthly payments.', 'Recognize repayment strategies and debt traps.'],
      lessons: [
        l('Understand what you are agreeing to', ['Principal is the amount borrowed or remaining before interest. Interest is the borrowing charge. APR expresses annualized cost and may include certain fees, making it useful for comparing similar offers. A term is the repayment duration.', 'Student loans support education, auto loans fund vehicles, and personal loans can serve many purposes. Terms, protections, and eligibility vary. Auto loans are commonly secured by the vehicle; default can risk repossession. No category is automatically good debt.'], 'A course loan might support future earnings, but a student still compares expected benefits, borrowing amount, payment terms, and uncertainty about future income.', 'A useful purpose does not remove the need to compare cost and affordability.', q('Which amount is principal?', ['The amount borrowed before borrowing charges','Only the annual fee','Your monthly salary'],0,'Principal is the borrowed amount, distinct from interest and fees.')),
        l('Look beyond a small monthly payment', ['A longer term can lower monthly payments while increasing total interest. Compare the same loan amount using APR, required payments, total repayment, fees, and any variable-rate or early-repayment conditions.', 'Interest rates can be fixed or variable. A simple-interest illustration uses principal × annual rate × years, but installment loans usually calculate interest on a changing balance. Read the schedule rather than assuming the simple formula predicts every loan.'], 'Offer A requires 24 payments of 110: total 2,640. Offer B requires 36 payments of 80: total 2,880. With no other fees and the same amount borrowed, B has the lower payment but higher total repayment.', 'Affordable monthly payments and total cost both matter.', q('Which has the higher total repayment: 12 × 100 or 18 × 75?', ['12 × 100','They are equal.','18 × 75'],2,'1,350 is greater than 1,200.')),
        l('Make a repayment plan', ['With debt avalanche, you keep required payments on all debts and direct extra money to the highest interest rate first. With debt snowball, extra money targets the smallest balance first for visible wins. Compare motivation and cost while maintaining required payments.', 'Repeated short-term borrowing, high fees, rollover costs, and borrowing to cover another unaffordable payment can signal a debt trap. If payments become difficult, contact lenders or reputable nonprofit counseling services early. Consolidation is not automatically cheaper; compare fees and total costs.'], 'Two balances are 100 at 8% and 500 at 25%. Avalanche targets the 25% debt with extra payments; snowball targets the 100 balance. Both still cover required payments on each.', 'Choose a sustainable plan and seek help before a shortfall becomes a cycle.', q('Debt avalanche directs extra payments first to:', ['The smallest balance regardless of rate','The highest interest rate','A random account'],1,'Avalanche prioritizes the costliest rate after required payments.'))
      ],
      vocabulary: [['Principal','The borrowed amount or remaining balance before interest.'],['Interest rate','The rate used to calculate borrowing charges.'],['APR','An annualized borrowing cost measure that may include specified fees.'],['Loan term','The duration of the repayment agreement.'],['Secured loan','A loan backed by collateral that may be taken after default.'],['Collateral','Property pledged to support a loan.'],['Fixed rate','A rate that stays unchanged for the agreed period.'],['Variable rate','A rate that can change under the agreement.'],['Debt avalanche','Extra repayments target the highest interest rate first.'],['Debt snowball','Extra repayments target the smallest balance first.']],
      summary: 'Compare loan purpose, risks, APR, monthly affordability, and total repayment. Maintain required payments and choose an extra-payment strategy that you can sustain.',
      assessment: [
        q('You borrow 800. Before interest, the principal is:', ['80','800','880'],1,'Principal is the borrowed amount.'),
        q('Simple annual interest on 1,000 at 6% for one year is:', ['6','600','60'],2,'1,000 × 0.06 × 1 = 60.'),
        q('Twenty payments of 75 total:', ['1,500','750','95'],0,'20 × 75 = 1,500.'),
        q('A longer term with a lower payment can:', ['Guarantee lower total cost','Increase total interest paid','Remove all fees'],1,'Lower monthly payments can stretch interest over more time.'),
        q('Which debt should avalanche target with extra payments?', ['The newest','The smallest only','The highest interest rate'],2,'Cover required payments, then target the highest rate.'),
        q('Which debt should snowball target with extra payments?', ['The smallest balance','The highest rate only','The oldest always'],0,'Snowball emphasizes smaller balances first.'),
        q('A car secures an auto loan. If you default, what risk exists?', ['The lender must give another car.','The vehicle may be repossessed.','The debt becomes a gift.'],1,'Collateral may be taken according to applicable terms and law.'),
        q('A student loan is always beneficial regardless of cost:', ['True','True if advertised online','False; purpose, terms, and affordability matter'],2,'Education does not make every loan suitable.'),
        q('Borrowing repeatedly to cover unaffordable repayments can signal:', ['A debt trap','Guaranteed wealth','Higher earned income'],0,'New borrowing can deepen a repayment cycle.'),
        q('Before consolidating loans, compare:', ['Only the first payment','Fees, rates, terms, and total repayment','Only the lender logo'],1,'A smaller payment alone does not prove savings.')
      ], sources: [['CFPB debt tools','https://www.consumerfinance.gov/consumer-tools/debt-collection/'],['CFPB APR explanation','https://www.consumerfinance.gov/ask-cfpb/what-is-an-annual-percentage-rate-apr-and-why-is-it-higher-than-the-interest-rate-for-my-payday-loan-en-1625/']]
    },
    {
      id: 7, title: 'Investing Basics', icon: '07', description: 'Explore risk, diversification, and long-term growth.',
      introduction: 'People invest to pursue growth or income over time, accepting uncertainty. This module is educational and is not personalized investment advice. No return is guaranteed, and investments can lose value.',
      objectives: ['Distinguish stocks, bonds, and pooled funds.', 'Explain risk, diversification, and time horizon.', 'Understand compound growth and basic retirement-account concepts.'],
      lessons: [
        l('Know what you own', ['A stock is an ownership share in a company. Its value can rise or fall; some companies pay dividends. A bond is a debt investment: you lend to an issuer under stated terms, with risks including default and changing market value.', 'An ETF or mutual fund pools investors’ money into a portfolio. ETFs usually trade during market hours, while mutual funds generally transact at a price calculated after the trading day. Funds have costs and can be narrow or broad; a fund is not automatically diversified.'], 'Owning only a fund focused on one industry can still expose a student to that industry’s downturn, even though the fund holds several companies.', 'Understand the underlying holdings, risks, and costs—not just the product name.', q('A share of stock represents:', ['A guaranteed bank deposit','Ownership in a company','A promise that prices only rise'],1,'Stocks represent equity ownership with uncertain value.')),
        l('Match risk with time', ['Risk is the possibility that results differ from expectations, including losing money. Potentially higher returns generally involve greater uncertainty, not a promise of better outcomes. Money needed soon has less time to recover from a market drop.', 'Diversification spreads exposure across holdings and asset types. It can reduce concentration risk but cannot eliminate all losses. Long-term investing involves a patient plan; it does not mean ignoring costs, changing goals, or risk.'], 'Tuition is due in two months. Putting that money in a volatile stock could leave too little when the bill arrives, even if the company has exciting long-term prospects.', 'Time horizon and ability to absorb loss matter before choosing investments.', q('Diversification means:', ['Spreading exposure while recognizing losses are still possible','Buying only one popular stock','Guaranteeing a profit'],0,'Diversification reduces concentration, not all risk.')),
        l('Growth, costs, and account wrappers', ['Compounding means returns may build on past returns when reinvested. A hypothetical 1,000 growing by 5% each year becomes 1,102.50 after two years. Actual investment returns vary; a loss changes the path, and taxes or fees can reduce results.', 'Retirement accounts are account structures with locally defined tax and access rules, not investments by themselves. US examples include workplace 401(k) plans and IRAs. What you hold inside an account determines much of its investment risk. Eligibility, withdrawal rules, and tax treatment depend on jurisdiction.'], 'Two accounts hold the same fund but have different fees or tax rules. The investment may be identical while the account conditions differ. Learn both layers before deciding.', 'Separate the investment from the account that holds it, and treat projections as illustrations.', q('A retirement account automatically guarantees growth:', ['Yes','Only if its name is short','No; investments and account rules still matter'],2,'An account wrapper does not remove investment risk.'))
      ],
      vocabulary: [['Stock','A share of ownership in a company.'],['Bond','A debt investment in which an issuer owes payments under stated terms.'],['ETF','An exchange-traded pooled investment fund.'],['Mutual fund','A pooled investment fund typically priced once per trading day.'],['Diversification','Spreading exposure across holdings or asset types.'],['Risk','Uncertainty about results, including possible loss.'],['Return','The gain or loss on an investment over a period.'],['Time horizon','How long until money is expected to be needed.'],['Compounding','Returns building on earlier accumulated returns.'],['Retirement account','An account structure with rules intended for retirement saving.']],
      summary: 'Learn what an investment holds, how it can lose value, and how costs affect it. Diversification and a suitable time horizon help manage risk but do not guarantee returns. This is education, not personalized investment advice.',
      assessment: [
        q('A student needs tuition money next month. A volatile stock introduces:', ['No risk','Risk of insufficient funds when the bill is due','A guaranteed tuition payment'],1,'A short horizon leaves little time to recover from losses.'),
        q('A stock is:', ['An insured deposit','Always a fixed-interest loan','Ownership in a company'],2,'Stocks are equity ownership.'),
        q('Buying a bond generally means:', ['Lending to an issuer under terms','Owning all of a bank','Removing default risk'],0,'Bonds are debt investments.'),
        q('A fund holds only one industry. It is:', ['Automatically diversified across all industries','Still exposed to concentration risk','Unable to lose value'],1,'Multiple holdings in one sector can remain concentrated.'),
        q('Diversification guarantees no losses:', ['True','True for any ETF','False'],2,'Diversification cannot remove all market risk.'),
        q('At hypothetical fixed 5% annual growth, 100 after two years is:', ['110.25','110','105'],0,'100 × 1.05 × 1.05 = 110.25.'),
        q('A higher potential return generally comes with:', ['A guarantee','Greater uncertainty or risk','No tradeoff'],1,'Potential return is not a promise.'),
        q('A retirement account is best understood as:', ['Always one particular stock','A guaranteed return','An account structure that may hold investments'],2,'Account rules and underlying investments are different layers.'),
        q('When comparing similar funds, examine:', ['Holdings, risk, and fees','Only recent popularity','Only the name'],0,'Costs and exposure affect suitability and results.'),
        q('A classroom projection assumes 7% every year. It is:', ['A promise','An illustration, not a forecast or guarantee','A personalized recommendation'],1,'Actual returns are uncertain.')
      ], sources: [['Investor.gov diversification','https://www.investor.gov/introduction-investing/getting-started/asset-allocation'],['Investor.gov investing introduction','https://www.investor.gov/introduction-investing']]
    },
    {
      id: 8, title: 'Taxes & Income', icon: '08', description: 'Make sense of paychecks and basic tax terminology.',
      introduction: 'Pay and taxes are connected, but the amount you earn is not always the amount you can spend. This is general education; W-2 and 1099 are United States examples, not worldwide forms or personalized tax guidance.',
      objectives: ['Distinguish gross and net income.', 'Read a simple paycheck.', 'Understand withholding and common US income documents.'],
      lessons: [
        l('Read from gross to net', ['Gross pay is earnings before deductions. Net pay is the amount remaining after deductions, such as taxes, insurance premiums, or retirement contributions. A payslip often separates this period’s amounts from year-to-date totals.', 'For hourly work, gross wages can be hours × hourly rate before additions or local overtime rules. Check the pay period, hours, rate, deductions, and deposit amount. If something is wrong, ask payroll through an official channel.'], 'A student works 20 hours at 15 per hour: 300 gross. With 35 tax withholding and 10 other deductions, net pay is 255. These are invented amounts, not a real tax rate.', 'Use net pay for spending plans and review the details behind it.', q('Gross pay is 500 with total deductions of 80. Net pay is:', ['580','420','80'],1,'500 − 80 = 420.')),
        l('Understand why money is withheld', ['Taxes fund public services and obligations, such as infrastructure and education. Income tax is a tax on taxable income under a jurisdiction’s rules. Tax systems, rates, allowances, and filing requirements vary.', 'Withholding is money collected from pay and sent toward taxes during the year. It is generally a prepayment, not necessarily the final amount owed. A tax return may reconcile payments with the final calculation; a refund is not automatically extra employer pay.'], 'Two people with equal gross pay can have different net pay because their benefits, withholding, and circumstances differ.', 'Withholding and final tax liability are related but not identical.', q('Tax withholding is best described as:', ['Always the exact final tax bill','A bonus','Money paid toward taxes during the year'],2,'The final amount can differ after the relevant calculation.')),
        l('Keep records and recognize forms', ['In the United States, employers generally provide a W-2 summarizing wages and certain taxes withheld. The 1099 family reports various other payments; for example, 1099-NEC can report nonemployee compensation. A 1099 is not simply a second name for a W-2.', 'Freelance income may arrive without tax withheld. Keep records of receipts and expenses, and check official local requirements for reporting and any advance payments. Whether income is taxable does not depend solely on receiving a form. Do not assume another country uses US rules.'], 'Kai has a campus job and freelance design work. Kai keeps payroll statements and freelance records separately, then checks the relevant official tax guidance.', 'Know the source of your income and keep the supporting records.', q('A freelancer receives money with no tax deducted. Which assumption is unsafe?', ['Records should be kept.','No withholding means no possible tax obligation.','Official local rules should be checked.'],1,'Income may still have reporting and tax obligations.'))
      ],
      vocabulary: [['Gross income','Earnings before deductions.'],['Net income','Income remaining after deductions in the relevant context.'],['Pay period','The span of work covered by a paycheck.'],['Deduction','An amount subtracted from gross pay.'],['Withholding','Money collected from payments toward taxes.'],['Income tax','Tax on taxable income under local rules.'],['W-2','A US form reporting employee wages and certain taxes withheld.'],['1099','A US family of forms reporting various types of payments.'],['Year to date','The cumulative amount from the start of the year through now.'],['Tax return','A filing used to report information and calculate taxes under local rules.']],
      summary: 'Read gross pay, deductions, and net pay separately. Withholding is a payment toward taxes; keep income records and use official guidance for the country where rules apply.',
      assessment: [
        q('Ten hours at 18 per hour gives gross wages of:', ['180','18','28'],0,'10 × 18 = 180 before deductions.'),
        q('Gross pay is 800 and deductions are 140. Net pay is:', ['940','660','140'],1,'800 − 140 = 660.'),
        q('Which amount is usually most useful for your spending budget?', ['Gross pay before all deductions','Year-to-date gross pay only','Take-home pay'],2,'Take-home pay is available after payroll deductions.'),
        q('Withholding is:', ['A payment toward taxes during the year','Always a fee paid to a private bank','Always the exact final liability'],0,'Final tax calculations may differ.'),
        q('A US W-2 generally reports:', ['Only a credit limit','Employee wages and certain taxes withheld','Only savings interest'],1,'W-2 is an employee wage and tax statement.'),
        q('The US 1099 family:', ['Is used worldwide for every paycheck','Always proves no tax is owed','Reports various kinds of payments'],2,'Different 1099 forms cover different payments.'),
        q('Freelance income arrives without withholding. You should:', ['Keep records and check applicable obligations','Assume it can never be taxable','Ignore the income entirely'],0,'No withholding does not remove possible obligations.'),
        q('A payslip has this-period and year-to-date totals. Year to date means:', ['Only the current week','Cumulative totals from the year’s start','Next year’s estimated income'],1,'It accumulates amounts through the current period.'),
        q('Two equal gross paychecks can have different net pay because:', ['Math never applies to pay','One must be fraudulent','Deductions and circumstances can differ'],2,'Benefits and withholding can change net pay.'),
        q('A learner outside the US sees W-2 guidance. They should:', ['Check their own country’s rules and forms','Assume W-2 applies everywhere','Stop keeping records'],0,'Forms and requirements are jurisdiction-specific.')
      ], sources: [['IRS tax withholding','https://www.irs.gov/payments/tax-withholding'],['IRS wage income','https://www.irs.gov/taxtopics/tc401']]
    },
    {
      id: 9, title: 'Insurance & Financial Protection', icon: '09', description: 'Understand coverage and prepare for costly surprises.',
      introduction: 'Insurance transfers specified financial risks to an insurer in exchange for payments. It does not cover everything, so understanding the policy is part of protecting yourself.',
      objectives: ['Explain premiums, deductibles, and limits.', 'Identify the purpose of common coverage types.', 'Compare protection with costs and exclusions.'],
      lessons: [
        l('Understand the agreement', ['A premium is the price you pay to keep a policy active. A deductible is an amount you pay toward covered costs before certain benefits apply. Some coverage can operate differently, so read the terms.', 'A coverage limit caps what a policy pays under specified conditions. Exclusions identify losses it does not cover. A claim is a request for benefits after an event. Insurance manages the financial impact of risk; it does not prevent every event.'], 'In a simplified covered claim with a 1,200 loss and a 200 deductible, the insurer pays 1,000 if there are no other limits or cost-sharing terms.', 'A paid premium does not mean every cost will be reimbursed.', q('In a simplified covered 900 loss with a 100 deductible and no other restrictions, insurer payment is:', ['900','100','800'],2,'900 − 100 = 800.')),
        l('Match coverage to the risk', ['Health insurance helps cover eligible medical costs; networks, copays, coinsurance, and limits affect what you pay. Auto coverage may include liability for harm to others and separate protection for your vehicle. Local requirements differ.', 'Renters insurance can cover personal belongings and certain liability risks; a landlord’s building policy generally does not replace your own belongings coverage. Life insurance pays a stated benefit after an insured death under policy terms, often to help people who depend on that income.'], 'A student renting a room checks whether belongings and personal liability are covered, rather than assuming the landlord’s policy protects a stolen laptop.', 'Choose coverage based on the loss you need help absorbing.', q('Which policy type commonly addresses a renter’s personal belongings?', ['The landlord’s building policy alone','Renters insurance','Life insurance'],1,'Renters policies commonly include personal property, subject to terms.')),
        l('Compare the whole policy', ['A lower premium can come with a higher deductible, narrower coverage, or a smaller network. Compare the risks covered, exclusions, limits, claims process, and money you would need to pay yourself.', 'Keep policy details and an inventory of important possessions in a safe place. Review protection when you move, buy a car, or gain dependents. Report claims truthfully and use official insurer channels. Emergency savings can help pay deductibles and costs not insured.'], 'Plan A costs less each month but has a 1,000 deductible. Plan B costs more but has a 250 deductible. A student compares both ongoing affordability and ability to cover a claim—not just the cheapest premium.', 'Protection works best when you understand both the coverage and your share.', q('Which makes a policy comparison meaningful?', ['Only looking at the premium','Assuming all insurers cover everything','Comparing premiums, deductibles, limits, and exclusions'],2,'The full terms determine protection and out-of-pocket risk.'))
      ],
      vocabulary: [['Insurance','An agreement covering specified financial risks under policy terms.'],['Premium','The price paid to keep insurance active.'],['Deductible','The amount you pay toward covered costs before certain benefits apply.'],['Claim','A request for benefits under a policy.'],['Coverage limit','The maximum payment under stated policy conditions.'],['Exclusion','An event or cost a policy does not cover.'],['Liability coverage','Protection for certain responsibilities for harm to others.'],['Copay','A fixed amount paid for an eligible service under some health plans.'],['Coinsurance','A percentage share of eligible costs paid under policy terms.'],['Beneficiary','A person or entity designated to receive a benefit.']],
      summary: 'Compare premiums with deductibles, limits, and exclusions. Match coverage to your circumstances and keep funds available for your share of costs.',
      assessment: [
        q('The regular cost of maintaining a policy is the:', ['Deductible','Premium','Claim'],1,'Premiums pay for the policy.'),
        q('Covered loss 2,000 minus deductible 500, with no other restrictions, gives insurer payment of:', ['2,500','500','1,500'],2,'2,000 − 500 = 1,500.'),
        q('A policy exclusion means:', ['A stated loss is not covered','Every claim is fully paid','The premium disappears'],0,'Exclusions define things outside coverage.'),
        q('A landlord insures the building. Your belongings:', ['Are always fully insured by that policy','May need your own renters coverage','Can no longer be stolen'],1,'Building insurance generally does not substitute for renters property coverage.'),
        q('Auto liability coverage generally concerns:', ['Only your fuel costs','Your savings yield','Specified harm you cause to others'],2,'Liability addresses responsibility for injury or damage under terms.'),
        q('Life insurance may help:', ['People financially dependent on the insured after a covered death','Guarantee stock returns','Pay every current grocery bill'],0,'Death benefits may support beneficiaries.'),
        q('A lower premium and much higher deductible should prompt:', ['No further questions','A check of whether you could pay that deductible','An assumption of better coverage'],1,'Lower ongoing cost can shift more claim cost to you.'),
        q('Health insurance premiums mean every service is free:', ['Always','Only on weekdays','No; cost sharing and coverage rules can apply'],2,'Premiums do not eliminate all out-of-pocket costs.'),
        q('A useful time to review coverage is:', ['When moving or gaining dependents','Never after buying it','Only after every policy expires'],0,'Life changes can alter protection needs.'),
        q('An emergency fund and insurance can work together because:', ['Insurance makes all saving useless','Savings can cover deductibles and uncovered costs','Savings guarantee every claim is accepted'],1,'They address different parts of financial risk.')
      ], sources: [['NAIC policy guide','https://content.naic.org/article/consumer-insight-understanding-your-homeowners-or-renters-policy'],['NAIC health plan guide','https://content.naic.org/sites/default/files/publication-consumer-using-your-health-plan.pdf']]
    },
    {
      id: 10, title: 'Financial Planning & Wealth Building', icon: '10', description: 'Connect today’s habits to your longer-term direction.',
      introduction: 'A financial roadmap connects your money habits with the life you want to build. Wealth usually develops gradually through many decisions, and progress depends on opportunities and circumstances as well as effort.',
      objectives: ['Organize goals across time horizons.', 'Balance protection, debt, saving, and growth.', 'Create a realistic roadmap and review routine.'],
      lessons: [
        l('Start with your destination and baseline', ['A short-term goal may be next semester’s fees; a medium-term goal could be a vehicle in several years; a long-term goal could be retirement. These categories are flexible. Write an amount and deadline for each goal.', 'Review income, expenses, assets, liabilities, and obligations. Set priorities when goals compete. A roadmap might start with essential bills and a small cushion, then balance debt repayment and future saving based on costs and needs. There is no universal sequence for every person.'], 'Rae lists 200 for books in four months, 2,000 for moving in two years, and a longer-term retirement goal. Each needs a different timeline and approach.', 'A useful roadmap starts with your actual position and named goals.', q('Which is the clearest medium-term goal?', ['Become successful','Save a specified amount for moving in two years','Spend without tracking'],1,'A purpose, amount, and timeframe make planning possible.')),
        l('Build capacity and resilience', ['Wealth can grow by keeping some income, reducing costly debt, and using suitable saving or investing approaches over time. Emergency reserves and insurance can help protect against setbacks. Investment growth is uncertain and should fit the goal’s timeframe and risk.', 'Career and income growth also matter: skills, education, experience, and job choices can change earning capacity. Evaluate training cost, completion likelihood, and realistic opportunities instead of assuming every expensive course pays off. Major purchases include ongoing costs, not only the purchase price.'], 'A car costs 3,000 to buy, but fuel, insurance, maintenance, and parking also affect affordability. Rae includes these in the monthly plan before deciding.', 'Consider income opportunities, protection, and total ownership costs together.', q('A major purchase is affordable only because you can pay its sticker price. What is missing?', ['The color','Nothing','Ongoing costs and effects on other goals'],2,'Ownership costs can strain a budget after the purchase.')),
        l('Create your first roadmap', ['Write one next action for each priority: track spending this week, set up an affordable saving transfer, compare debt costs, or research a training option. Add a review date and a way to measure progress.', 'Review after important changes and at regular intervals. Update assumptions when rent, income, family needs, or deadlines change. Beware of guaranteed fast-wealth claims; gradual progress and informed decisions are more reliable than promises. Net worth can move unevenly and is not a measure of personal value.'], 'Rae chooses a monthly review: update balances, compare actual saving with the goal, and revise the next month’s contribution. A lower-income month leads to a revised plan, not abandoning every goal.', 'Turn the roadmap into small actions and revisit it as life changes.', q('Income drops temporarily. What is a constructive response?', ['Review priorities and adjust contributions.','Ignore the change.','Borrow for every optional expense.'],0,'A roadmap is meant to adapt.'))
      ],
      vocabulary: [['Financial roadmap','A plan linking goals, actions, resources, and review dates.'],['Short-term planning','Planning for relatively near needs and goals.'],['Medium-term planning','Planning for goals between immediate needs and distant aims.'],['Long-term planning','Planning for goals further in the future.'],['Net worth','Assets minus liabilities at a point in time.'],['Resilience','Capacity to handle and recover from a financial setback.'],['Earning capacity','The ability to generate income through work or other activity.'],['Total ownership cost','Purchase price plus ongoing costs of owning and using something.'],['Milestone','A smaller measurable target on the way to a larger goal.'],['Review date','A planned time to check progress and update assumptions.']],
      summary: 'Connect specific goals to timelines, protect against setbacks, compare debt and ownership costs, and explore earning opportunities. Review your roadmap regularly and expect to adjust it.',
      assessment: [
        q('A useful roadmap includes:', ['Goals, actions, and review dates','Only a wish','Only a stock tip'],0,'A roadmap links intentions to action.'),
        q('Saving 900 over 18 months from zero requires monthly:', ['90','50','18'],1,'900 ÷ 18 = 50, ignoring growth.'),
        q('A 2,000 vehicle also needs insurance and maintenance. These are:', ['Irrelevant','Guaranteed free','Part of total ownership cost'],2,'Affordability includes ongoing costs.'),
        q('Which can improve earning capacity?', ['Relevant skills and realistic career opportunities','Ignoring every job requirement','Guaranteed investment rumors'],0,'Skills and opportunities can affect future earnings.'),
        q('An expensive course claims guaranteed high earnings. What is sensible?', ['Borrow immediately.','Evaluate costs, evidence, and realistic outcomes.','Assume all training is worthless.'],1,'Costs and likely benefits need examination.'),
        q('An emergency reserve helps a roadmap by:', ['Eliminating every risk','Guaranteeing a high return','Reducing disruption from unexpected costs'],2,'Reserves can protect other goals from setbacks.'),
        q('Income changes. Your roadmap should:', ['Be reviewed and adjusted','Remain fixed forever','Ignore essential bills'],0,'Plans should reflect current circumstances.'),
        q('A promise of guaranteed rapid wealth deserves:', ['Immediate payment','Careful skepticism and verification','No questions'],1,'High guaranteed-return claims can be misleading or fraudulent.'),
        q('Short-, medium-, and long-term goals:', ['Must all use the same approach','Must have identical deadlines','May require different saving and risk choices'],2,'Timeline affects appropriate planning.'),
        q('Which is a useful first action?', ['Schedule a monthly review of balances and goals','Wait for a perfect plan forever','Measure success only against classmates'],0,'Small, repeatable actions make the roadmap usable.')
      ], sources: [['CFPB financial goals resources','https://www.consumerfinance.gov/consumer-tools/educator-tools/your-money-your-goals/'],['Investor.gov education','https://www.investor.gov/introduction-investing']]
    }
  ];
})();
