const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { spawn } = require('node:child_process');
const path = require('node:path');
fs.mkdirSync('test-results',{recursive:true});
const marker = path.resolve('test-results/coach-provider.jsonl');
const servers = [];
async function start(port, mock, apiBase='') {
  const child=spawn(process.execPath,['tests/coach-server.mjs'],{env:{...process.env,PORT:String(port),COACH_TEST_MARKER:mock?marker:'',MONEYGUIDE_ALLOWED_ORIGINS:'http://127.0.0.1:3103',COACH_TEST_API_BASE:apiBase},stdio:['ignore','pipe','pipe']});
  servers.push(child);
  const logs=[]; child.stderr.on('data', data=>logs.push(data.toString()));
  await new Promise((resolve,reject)=>{
    const timer=setTimeout(()=>reject(new Error('Server startup timeout')),30000);
    child.stdout.on('data',data=>{if(data.toString().includes('MoneyGuide:')){clearTimeout(timer);resolve();}});
    child.on('error',reject);child.on('exit',code=>{if(code)reject(new Error('Server exited '+code));});
  });
  return {base:`http://127.0.0.1:${port}`,logs};
}
(async()=>{
 let browser;
 try {
  const unavailable=await start(3101,false);
  const available=await start(3102,true);
  browser=await chromium.launch({channel:'chrome',headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
  page.setDefaultTimeout(20000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(unavailable.base);
  await page.locator('#open-coach').click();
  await page.locator('#coach-input').fill('What is a credit score?');
  const request=page.waitForResponse(response=>response.url().endsWith('/api/moneyguide'));
  await page.locator('#coach-send').click();
  assert.equal((await request).status(),503);
  await page.waitForFunction(()=>document.querySelector('#coach-error').textContent.includes('NVIDIA_API_KEY'));
  assert.equal(await page.locator('.chat-user').count(),1);
  assert.equal(await page.locator('#coach-send').isEnabled(),true);
  assert.match(unavailable.logs.join(''),/AI_NOT_CONFIGURED/);
  await page.screenshot({path:'test-results/coach-configuration.png'});
  await page.goto(available.base);
  await page.screenshot({path:'test-results/coach-homepage.png'});
  await page.locator('[data-open-coach]').click();
  assert.equal(await page.locator('#onboarding-dialog').isVisible(),false);
  await page.getByRole('button',{name:'What is a credit score?',exact:true}).click();
  assert.equal(await page.locator('#coach-input').inputValue(),'What is a credit score?');
  await page.locator('#coach-input').press('Enter');
  assert.equal(await page.locator('.chat-user').count(),1);
  assert.equal(await page.locator('#coach-send').isDisabled(),true);
  assert.match(await page.locator('#coach-status').innerText(),/thinking/);
  await page.locator('.chat-assistant').waitFor();
  assert.match(await page.locator('.chat-assistant').innerText(),/emergency fund/);
  await page.locator('#coach-input').fill('How do I start?');
  await page.locator('#coach-send').click();
  await page.waitForFunction(()=>document.querySelectorAll('.chat-assistant').length===2);
  const calls=fs.readFileSync(marker,'utf8').trim().split('\n').map(JSON.parse);
  assert.equal(calls.length,2);
  assert.equal(calls[0].method,'POST');
  assert.equal(calls[1].payload.messages.length,5);
  assert.match(calls[0].payload.messages[1].content,/Beginner/);
  assert.doesNotMatch(JSON.stringify(calls),/firstName/);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#coach-dialog').isVisible(),false);
  await page.locator('#open-coach').click();
  assert.equal(await page.locator('.chat-message').count(),4);
  await page.screenshot({path:'test-results/coach-desktop-dark.png'});
  await page.locator('#coach-clear').click();
  assert.equal(await page.locator('.chat-message').count(),0);
  await page.locator('#coach-input').fill('Help me budget');
  await page.locator('#coach-send').click();
  await page.locator('#coach-clear').click();
  await page.waitForTimeout(900);
  assert.equal(await page.locator('.chat-message').count(),0);
  await page.locator('#coach-close').click();
  await page.locator('#theme-toggle').click();
  await page.locator('#open-coach').click();
  await page.screenshot({path:'test-results/coach-desktop-light.png'});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  const box=await page.locator('#coach-dialog').boundingBox();
  assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=390&&box.y+box.height<=844);
  await page.locator('#coach-input').fill('What is saving?');
  await page.locator('#coach-send').click();
  await page.locator('.chat-assistant').waitFor();
  await page.screenshot({path:'test-results/coach-mobile.png'});
  await page.setViewportSize({width:640,height:520});
  assert.ok((await page.locator('#coach-history').boundingBox()).height >= 60);
  await page.screenshot({path:'test-results/coach-short-screen.png'});
  await page.locator('#coach-close').click();
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>localStorage.setItem('moneyguide.profile',JSON.stringify({firstName:'PrivateName',currency:'USD',goal:'Buy a car',knowledge:'Advanced'})));
  await page.goto(available.base+'/dashboard.html');
  await page.locator('#demo-budget').click();
  await page.locator('#generate-plan').click();
  await page.locator('#plan-answer').waitFor({state:'visible'});
  await page.locator('#explain-plan').click();
  await page.getByRole('heading',{name:'Why this plan?'}).waitFor();
  await page.locator('#open-coach').click();
  await page.locator('#coach-input').fill('Explain my savings timeline');
  await page.locator('#coach-send').click();
  await page.locator('.chat-assistant').waitFor();
  const latest=JSON.parse(fs.readFileSync(marker,'utf8').trim().split('\n').at(-1));
  assert.match(latest.payload.messages[1].content,/"months":8/);
  assert.match(latest.payload.messages[1].content,/Advanced/);
  assert.doesNotMatch(JSON.stringify(latest),/PrivateName/);
  await page.locator('#coach-close').click();
  await page.locator('#header-currency').selectOption('KES');
  await page.locator('#open-coach').click();
  assert.equal(await page.locator('.chat-message').count(),0);
  assert.match(await page.locator('#coach-context').innerText(),/KES/);
  assert.deepEqual(errors,[]);
  assert.equal(available.logs.length,0);
  // Separate static frontend and API: real browser CORS preflight, no route mocking of the API.
  const frontend=await start(3103,false,available.base);
  const remote=await browser.newPage();
  const remoteErrors=[];remote.on('pageerror',error=>remoteErrors.push(error.message));
  await remote.goto(frontend.base);
  await remote.locator('#open-coach').click();
  await remote.locator('#coach-input').fill('How can I save $3,000?');
  const crossPost=remote.waitForResponse(response=>response.url()===available.base+'/api/moneyguide'&&response.request().method()==='POST');
  await remote.locator('#coach-send').click();
  assert.equal((await crossPost).status(),200);
  const preflights=fs.readFileSync(marker+'.cors','utf8').trim().split('\n').map(JSON.parse);
  assert.ok(preflights.some(request=>request.origin===frontend.base&&request.method==='OPTIONS'&&request.status===204));
  await remote.locator('.chat-assistant').waitFor();
  assert.deepEqual(remoteErrors,[]);
  await remote.close();
  // Static hosting errors must provide an actionable message, not a JSON parse failure.
  await page.route('**/api/moneyguide',route=>route.fulfill({status:404,contentType:'text/html',body:'Not found'}));
  await page.locator('#coach-input').fill('What is saving?');await page.locator('#coach-send').click();
  await page.waitForFunction(()=>document.querySelector('#coach-error').textContent.includes('GitHub Pages'));
  console.log('PASS: real browser HTTP -> backend -> stubbed NVIDIA transport -> displayed answer; multi-turn context; guest/profile; plans/explanations; configuration and static-host errors; cancellation; keyboard; themes; mobile; no JS errors. Cross-origin OPTIONS/POST also passed. Live NVIDIA not tested: no key.');
 }finally{if(browser)await browser.close();for(const child of servers)child.kill();}
})().catch(error=>{console.error(error);process.exitCode=1;});
